### ISSUE TITLE
Support pagination for SmoothScrolling

### ISSUE THREAD

**Issue by andrea-prearo** [andrea-prearo/SwiftExamples#11]
In order to optimize data fetching and loading, the webservice to showcase SmoothScrolling should support pagination. This will be done in two steps:
1) Support pagination with the current data format
2) Update the webservice (`v2`) to return pagination information with each page

**Comment by StackHelp** [comment]
Works great for me. Thanks :) Is there any example with sd_webimage or with Kingfisher?

**Comment by andrea-prearo** [comment]
You're welcome!

I don't have an example with Kingfisher or SDWebImage. Integrating any of those frameworks shouldn't be too difficult. I think you can just swap out calling [`UIImage.downloadImageFromUrl(...)`](https://github.com/andrea-prearo/SwiftExamples/blob/master/SmoothScrolling/Client/Shared/Prefetch/ImageLoadOperation.swift#L27) with the particular async image downloading method that is required.

At the moment, the code doesn't support deleting and/or inserting cells. The current example(s) are focused on read only functionality.

**Comment by StackHelp** [comment]
Yeah done with SDWebImage. Thanks

**Comment by StackHelp** [comment]
@andrea-prearo One question.. In this demo, the page starts from 0 or 1?

**Comment by StackHelp** [comment]
@andrea-prearo "At the moment, the code doesn't support deleting and/or inserting cells. The current example(s) are focused on read-only functionality." Is there any chance we can make it read/write functionality with this? I'll try though and If possibly done with the solution then let you know

**Comment by andrea-prearo** [comment]
@StackHelp The functionality to insert/delete cells can definitely be added. The easiest way could be to add a couple of ad hoc methods to the`UserViewModelController` to insert and delete cells and modify the private `viewModels`. array.

**Comment by StackHelp** [comment]
@andrea-prearo I am trying it right now. Will let you know If I am successful in it. Thanks
